[package]
name = "aoc-2021-14"
version = "0.1.0"
authors = ["liskaant <liskaant@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
regex = "1"
lazy_static = "1"
